name: Test with pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have a requirements.txt file, uncomment the next line
        pip install scikit-learn numpy pandas pytest fastapi uvicorn httpx
    - name: Test with pytest
      run: |
        pytest tests/test_main.py
        pytest tests/test_train_model.py
